### PR TITLE
Define rust::isize with Windows support

### PR DESCRIPTION
**Pull request by dtolnay**
Hybrid of https://github.com/dtolnay/cxx/commit/15b5b10763219ba6386abae073a11dd6b06a8ea1 and https://github.com/dtolnay/cxx/commit/ef1bf1822c243a38832602b75d21d3da1fd77804 and https://github.com/dtolnay/cxx/pull/96#issuecomment-612150188.

cc @myronahn @AlesTsurko
closes #96

### CODE REVIEW

**Comment by dtolnay** [comment]
Following up on `_WIN32` vs `_MSC_VER` from https://github.com/dtolnay/cxx/pull/96#issuecomment-612146914: it sounds like `_WIN32` is defined when building *for* windows with any compiler, while `_MSV_VER` is defined when building specifically with the Microsoft compiler. Unclear which is more appropriate in this case but I would think `_WIN32` because building the same code with a different compiler on windows isn't going to cause a different set of headers to be included (is it?). @myronahn @AlesTsurko I would appreciate any insight on this.

**Comment by AlesTsurko** [comment]
Really can't say something reasonable about it. I'm not an expert in the Windows development.

Anyway, if this is true:
> _WIN32 is defined when building for windows with any compiler, while _MSV_VER is defined when building specifically with the Microsoft compiler.

the `_WIN32` is the correct choice.

I used the Visual Studio's/Microsoft compiler to check #96

**Comment by myronahn** [comment]
I'm not an expert either but `_WIN32` sounds like the better choice.

**Comment by myronahn** [comment]
I believe `BaseTsd.h` is in the Windows SDK and so theoretically independent of the Microsoft Compiler.  `_WIN32` is probably more appropriate in this case.

**Pull request merged**
