### PR TITLE
Support raw pointers in cxx::bridge.

### LINKED ISSUE #164: Allow raw pointers in extern fn signature
See https://github.com/dtolnay/cxx/issues/122#issuecomment-615372359 for the rationale.

```rust
mod ffi {
    extern "C" {
        type T;
        unsafe fn f(_: *mut T);
    }
    extern "Rust" {
        unsafe fn g(_: *mut T);
    }
}
```

The presence of `*const` or `*mut` in a function argument should enforce that the function is marked unsafe.

### PR DESCRIPTION
**Pull request by adetaylor**
This allows raw pointers to types to be passed into and out of
cxx::bridge extern "C++" APIs. As normal with raw pointers in Rust,
there are no safety or lifetime guarantees.

Passing a raw pointer into such an API requires that the
function be marked "unsafe".

Fixes #164.

### CODE REVIEW

**Comment by adetaylor** [comment]
dtolnay@ I'm terribly sorry to ping. Is there anything I can do to make it easier for you to accept this? If it requires rework but you don't have time to detail exactly what is wrong, feel free to give me rushed, vague instructions and I shall try to do my best to reverse engineer them :)

**Comment by dtolnay** [comment]
I haven't gotten a chance to look yet -- just lots of competing priorities on lots of projects. I was hoping that a use case for this might come up in my codebase to justify prioritizing, but so far we haven't needed it. I will make some time to review. Meanwhile you are a collaborator on this repo so you're welcome to help shepherd any of the other PRs. ;)

**Comment by adetaylor** [comment]
OK, successfully incentivized, I'll see if I feel qualified to guide any of the PRs which are outstanding or come in during the next few days! Thanks!

**Review by dtolnay — CHANGES_REQUESTED** [review]
Thank you, this is great. I regret that it took me so long to get back to this.

**Comment by dtolnay** [comment]
I am merging this and will follow up with my own fixes. Thanks again!

**Comment by adetaylor** [comment]
> I am merging this and will follow up with my own fixes. Thanks again!

Thanks, but you really didn't have to - I would have been more than happy to act on your excellent review feedback (as ever). Thanks a ton!

**Pull request merged**
