### PR TITLE
Add output

### PR DESCRIPTION
**Pull request by sayrer**
I started using this and everything worked in Bazel, except for a linkage error right at the end. This is because it's difficult to make cc::Build work well with Bazel's various toolchain and cross-compilation settings. It's way easier just to use the source file.

I manually added the cxxbridge.cc source file to my build, and it works. This patch adds another option to emit the cxxbridge.cc file, but I left it printing the wrong thing for now. This is because the relative include path in the .cc file doesn't make a ton of sense. It would be easier if the two files were just next to each other, either by moving the header, or by linking it into src/.

### CODE REVIEW

**Comment by sayrer** [comment]
I don't really have an opinion on how to best accomplish this task. The Bazel rules_rust don't accept .cc sources as inputs to Rust rules right now. Providing Buck/Bazel rules in the repo would be one way, another would be very granular command line outputs (as in this patch). There is also a way to create a cc_library as you suggest, but it wouldn't stay in sync with the Cargo files automatically, as it does with the command line outputs.

**Comment by dtolnay** [comment]
cc::Build shouldn't be involved -- build.rs is only needed for when using Cargo.

Can you clarify why running the cmd to emit cxxbridge.cc would stay more up to date than a cc_library rule that gets cxxbridge.cc from the vendored cxx source tree? I would think both of those stay equally up to date when you update the vendored sources.

**Comment by sayrer** [comment]
Bazel has a de facto standard tool called "cargo raze", that creates BUILD.bazel files from Cargo lockfiles. https://github.com/google/cargo-raze

I can get this crate working using something like this in a Cargo raze Cargo.toml file:
```
[raze.crates.cxx.'0.1.2']
gen_buildrs = true
buildrs_additional_environment_variables = [
	"OPT_LEVEL=3",
	"HOST=x86_64-apple-darwin",
]
data_attr = 'glob(["**/*.h", "**/*.cc"])'
```

This matters to me, because I need to cross compile (target does work), and I need cache build artifacts. I would need to write a pretty complicated Bazel file to make it work as it stands.

`cargo raze` currently works perfectly with everything in the giant list below (on rustc trunk, with a few extra in-Cargo.toml rules for proc-macro2), except for cxx, because it crosses the rules_cc / rules_rust boundaries in ways that were not anticipated. I could create a cc_library rule that would work, but it would require continuing maintenance to track cxx's Cargo.toml. This issue is tracked here: https://github.com/google/cargo-raze/issues/41

```
Generated .//vendor/ansi_term-0.11.0/BUILD.bazel successfully
Generated .//vendor/anyhow-1.0.26/BUILD.bazel successfully
Generated .//vendor/atty-0.2.14/BUILD.bazel successfully
Generated .//vendor/bitflags-1.2.1/BUILD.bazel successfully
Generated .//vendor/block-buffer-0.7.3/BUILD.bazel successfully
Generated .//vendor/block-padding-0.1.5/BUILD.bazel successfully
Generated .//vendor/byte-tools-0.3.1/BUILD.bazel successfully
Generated .//vendor/byteorder-1.3.2/BUILD.bazel successfully
Generated .//vendor/c2-chacha-0.2.3/BUILD.bazel successfully
Generated .//vendor/cbindgen-0.12.2/BUILD.bazel successfully
Generated .//vendor/cc-1.0.50/BUILD.bazel successfully
Generated .//vendor/cfg-if-0.1.10/BUILD.bazel successfully
Generated .//vendor/clap-2.33.0/BUILD.bazel successfully
Generated .//vendor/codespan-0.7.0/BUILD.bazel successfully
Generated .//vendor/codespan-reporting-0.7.0/BUILD.bazel successfully
Generated .//vendor/cxx-0.1.2/BUILD.bazel successfully
Generated .//vendor/cxxbridge-cmd-0.1.2/BUILD.bazel successfully
Generated .//vendor/cxxbridge-macro-0.1.2/BUILD.bazel successfully
Generated .//vendor/digest-0.8.1/BUILD.bazel successfully
Generated .//vendor/dtoa-0.4.5/BUILD.bazel successfully
Generated .//vendor/fake-simd-0.1.2/BUILD.bazel successfully
Generated .//vendor/generic-array-0.12.3/BUILD.bazel successfully
Generated .//vendor/getrandom-0.1.14/BUILD.bazel successfully
Generated .//vendor/heck-0.3.1/BUILD.bazel successfully
Generated .//vendor/hermit-abi-0.1.6/BUILD.bazel successfully
Generated .//vendor/idna-0.1.5/BUILD.bazel successfully
Generated .//vendor/itoa-0.4.5/BUILD.bazel successfully
Generated .//vendor/lazy_static-1.4.0/BUILD.bazel successfully
Generated .//vendor/libc-0.2.66/BUILD.bazel successfully
Generated .//vendor/link-cplusplus-1.0.1/BUILD.bazel successfully
Generated .//vendor/linked-hash-map-0.5.2/BUILD.bazel successfully
Generated .//vendor/log-0.4.0/BUILD.bazel successfully
Generated .//vendor/maplit-1.0.2/BUILD.bazel successfully
Generated .//vendor/matches-0.1.8/BUILD.bazel successfully
Generated .//vendor/opaque-debug-0.2.3/BUILD.bazel successfully
Generated .//vendor/pest-2.1.2/BUILD.bazel successfully
Generated .//vendor/pest_derive-2.1.0/BUILD.bazel successfully
Generated .//vendor/pest_generator-2.1.1/BUILD.bazel successfully
Generated .//vendor/pest_meta-2.1.2/BUILD.bazel successfully
Generated .//vendor/ppv-lite86-0.2.6/BUILD.bazel successfully
Generated .//vendor/proc-macro-error-0.4.3/BUILD.bazel successfully
Generated .//vendor/proc-macro-error-attr-0.4.8/BUILD.bazel successfully
Generated .//vendor/proc-macro2-1.0.8/BUILD.bazel successfully
Generated .//vendor/quote-1.0.2/BUILD.bazel successfully
Generated .//vendor/rand-0.7.3/BUILD.bazel successfully
Generated .//vendor/rand_chacha-0.2.1/BUILD.bazel successfully
Generated .//vendor/rand_core-0.5.1/BUILD.bazel successfully
Generated .//vendor/rand_hc-0.2.0/BUILD.bazel successfully
Generated .//vendor/redox_syscall-0.1.56/BUILD.bazel successfully
Generated .//vendor/remove_dir_all-0.5.2/BUILD.bazel successfully
Generated .//vendor/rustversion-1.0.2/BUILD.bazel successfully
Generated .//vendor/ryu-1.0.2/BUILD.bazel successfully
Generated .//vendor/serde-1.0.104/BUILD.bazel successfully
Generated .//vendor/serde_derive-1.0.104/BUILD.bazel successfully
Generated .//vendor/serde_json-1.0.46/BUILD.bazel successfully
Generated .//vendor/serde_yaml-0.7.5/BUILD.bazel successfully
Generated .//vendor/sha-1-0.8.2/BUILD.bazel successfully
Generated .//vendor/smallvec-1.2.0/BUILD.bazel successfully
Generated .//vendor/strsim-0.8.0/BUILD.bazel successfully
Generated .//vendor/structopt-0.3.8/BUILD.bazel successfully
Generated .//vendor/structopt-derive-0.4.1/BUILD.bazel successfully
Generated .//vendor/syn-1.0.14/BUILD.bazel successfully
Generated .//vendor/syn-mid-0.5.0/BUILD.bazel successfully
Generated .//vendor/tempfile-3.1.0/BUILD.bazel successfully
Generated .//vendor/termcolor-1.1.0/BUILD.bazel successfully
Generated .//vendor/textwrap-0.11.0/BUILD.bazel successfully
Generated .//vendor/thiserror-1.0.10/BUILD.bazel successfully
Generated .//vendor/thiserror-impl-1.0.10/BUILD.bazel successfully
Generated .//vendor/toml-0.5.6/BUILD.bazel successfully
Generated .//vendor/typenum-1.11.2/BUILD.bazel successfully
Generated .//vendor/ucd-trie-0.1.2/BUILD.bazel successfully
Generated .//vendor/unicode-bidi-0.3.4/BUILD.bazel successfully
Generated .//vendor/unicode-normalization-0.1.12/BUILD.bazel successfully
Generated .//vendor/unicode-segmentation-1.6.0/BUILD.bazel successfully
Generated .//vendor/unicode-width-0.1.7/BUILD.bazel successfully
Generated .//vendor/unicode-xid-0.2.0/BUILD.bazel successfully
Generated .//vendor/vec_map-0.8.1/BUILD.bazel successfully
Generated .//vendor/wasi-0.9.0+wasi-snapshot-preview1/BUILD.bazel successfully
Generated .//vendor/winapi-0.3.8/BUILD.bazel successfully
Generated .//vendor/winapi-i686-pc-windows-gnu-0.4.0/BUILD.bazel successfully
Generated .//vendor/winapi-util-0.1.3/BUILD.bazel successfully
Generated .//vendor/winapi-x86_64-pc-windows-gnu-0.4.0/BUILD.bazel successfully
Generated .//vendor/yaml-rust-0.4.3/BUILD.bazel successfully
Generated .//BUILD.bazel successfully
```

**Comment by dtolnay** [comment]
I am not familiar with cargo-raze but based on your explanation I don't feel that this PR is the right approach. If cargo-raze makes it complicated to augment its generated rules with your own cc_library rule to build just the cxxbridge.cc file, that should be fixed in cargo-raze.

Thanks anyway!

**Pull request closed without merging**
