### PR TITLE
Add c_str() member function for rust::String

### PR DESCRIPTION
**Pull request by dtolnay**
Matches https://en.cppreference.com/w/cpp/string/basic_string/c_str.
#224

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Oh neat, this is an elegant solution.  The only thing that makes me slightly uncomfortable about this is conceptually we may end up mutating data that might be owned by the Rust side under a regular non-`mut` reference, if we returned an `&String` right?  But OTOH this is really a sort of "interior mutability" that should be invisible to anything accessing Rust side.  So it's safe from that PoV.

**Comment by dtolnay** [comment]
You can't call this on a &amp;String because the member function is non-const.

**Comment by cgwalters** [comment]
> You can't call this on a &String because the member function is non-const.

OK right.  This will help in a few cases I have now at least, though I think the case of having C++ iterate over data owned by Rust is going to be very common in at least my code, but I am going to try out using CUtf8 as an extern type.

**Comment by bridiver** [comment]
is there a reason why `rust::Str` doesn't also have `c_str`? It would be much easier to work with in cpp without copying if it returned a null terminated string like `rust::String::c_str`

**Pull request merged**
