### PR TITLE
chore: clippy let-underscore-untyped

### PR DESCRIPTION
**Pull request by nyurik**
Clippy keeps complaining about
  https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_untyped

Seems like a noop, esp considering that @dtolnay has filed a bug in
  https://github.com/rust-lang/rust-clippy/issues/10411

One issue though is that MSRV in .clippy.toml is not matching the one in Cargo.toml:
* .clippy.toml:  msrv = "1.48.0"
* Cargo.toml: rust-version = "1.60"

Which one is the accurate one?  I would assume its the Cargo.toml, in which case it might be better to apply this change?

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
This lint was removed from clippy for being misguided, so I would prefer not to follow its guidance.

**Comment by nyurik** [comment]
@dtolnay thx, i wasn't sure if its applicable or not.  What about the difference in MSRV?

**Comment by dtolnay** [comment]
I think it's fine. Some of the crates in the workspace have a different supported rust-version from one another.

**Comment by nyurik** [comment]
> I think it's fine. Some of the crates in the workspace have a different supported rust-version from one another.

But if they are different, shouldn't clippy rules be relevant to each specific crate?  I honestly don't understand the need for a global clippy-only MSRV -- maybe there is some other reason I'm missing?

**Pull request closed without merging**
