### PR TITLE
impl UniquePtrTarget for T;

### LINKED ISSUE #236: Legitimate uses for UniquePtrs even if not currently expanded
https://github.com/dtolnay/cxx/issues/228#issuecomment-656459774 gives code like this (I've changed the type names but nothing else):

```rust
use cxx::UniquePtr;

#[cxx::bridge(namespace = base::test)]
pub mod ffi {
    extern "C" {
        include!("base/test/scoped_feature_list.h");
        
        type ScopedFeatureList;
        
        fn Init(self: &mut ScopedFeatureList);
    }
}

pub struct ScopedFeatureList {
    instance: UniquePtr<ffi::ScopedFeatureList>,
}

impl ScopedFeatureList {
    pub fn init(&mut self) {
        self.instance.Init();
    }
}
```

This doesn't compile because:
```
error[E0277]: the trait bound `features::ffi::ScopedFeatureList: cxx::private::UniquePtrTarget` is not satisfied
  --> ../../base/rs/src/features.rs:15:5
   |
15 |     instance: UniquePtr<ffi::ScopedFeatureList>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cxx::private::UniquePtrTarget` is not implemented for `features::ffi::ScopedFeatureList`
   | 
  ::: /Users/adetaylor/dev/chromium/src/out/Debug/../../third_party/rust/crates/cxx/src/unique_ptr.rs:14:8
   |
14 |     T: UniquePtrTarget,
   |        --------------- required by this bound in `cxx::UniquePtr`
```

This is because `expand_unique_ptr` never gets called, because no methods in the `ffi` block take a `UniquePtr<ScopedFeatureList>` as a parameter.

### PR DESCRIPTION
**Pull request by adetaylor**
Builds on top of #325. Fixes #236.

### CODE REVIEW

**Comment by sbrocket** [comment]
Can we do this without exposing - and requiring users to know - the internal trait names like `UniquePtrTarget`? In #308 dtolnay@ suggested something like `impl Vec<T>;` and `impl UniquePtr<T>;`.

**Comment by adetaylor** [comment]
Yes, probably, I will amend that way after I eventually rebase on top of your stuff.

**Comment by sbrocket** [comment]
One other thing to consider here. For Vec and Box after my PR #308, the following only fails at C++ compile time currently because we don't have traits similar to `UniquePtrTarget` and `VectorElement` for those that can be checked with a trait bound.

```
#[cxx::bridge]
mod here {
    struct Shared {
        z: usize,
    }
}

#[cxx::bridge]
mod there {
    type Shared = crate::here::Shared;

    extern "C" {
        fn c_take_rust_vec_shared(v: Vec<Shared>);
    }
}

fn main() {}
```

We might want to add those in a separate PR to improve the diagnostics, plus then we can point people at this option.

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR. :) I ended up merging #336 instead, which follows the approach from https://github.com/dtolnay/cxx/issues/312#issuecomment-696831431 of using `impl UniquePtr<T> {}` for a requested instantiation. As @sbrocket points out, this is more closely connected to the public API of the cxx crate and we avoid making the user learn a second set of names for the internal names of the traits.

**Comment by adetaylor** [comment]
Sounds good. Thank you!

**Pull request closed without merging**
